//! `vouch import` — translate an existing cc-allow config.
//!
//! Honest about what does and does not carry over. The two tools do not have the
//! same model, so a silent "translated!" would be a lie:
//!
//!   * PATH allowlists carry over directly — same idea, same globs.
//!   * cc-allow's construct switches map onto vouch constructs one-for-one.
//!   * COMMAND allowlists do NOT carry over. cc-allow gated on program NAMES;
//!     vouch gates on what a program DOES. A list of 66 trusted program names has
//!     no equivalent, and reproducing it would rebuild the exact mechanism that
//!     produced 575 prompts. These are reported as dropped, with the count.
//!   * The `[tools]` name-gate DOES have an equivalent now, and this importer
//!     does not yet write it. vouch has `tools.<name>` in the config and
//!     `[[tool]]` entries in the knowledge, and an unrecognised tool ASKS
//!     naming that setting rather than abstaining — abstaining was the same
//!     inversion as unmodelled programs, one level up (`route.rs`). Until the
//!     translation is written these are reported, not silently discarded, and
//!     the report says what to write by hand.
//!
//! Anything this cannot translate is listed in the report. Nothing is guessed.

use std::collections::BTreeMap;

#[derive(Debug, Default)]
pub struct Import {
    /// The generated vouch config.
    pub config: String,
    /// Human-readable notes: what carried, what did not, and why.
    pub notes: Vec<String>,
}

fn action_of(v: Option<&toml::Value>) -> Option<&str> {
    v.and_then(|x| x.as_str())
        .filter(|s| matches!(*s, "allow" | "ask" | "deny"))
}

/// cc-allow construct name -> vouch construct name.
fn construct_map(cc: &str) -> Option<&'static str> {
    match cc {
        "background" => Some("background"),
        "subshells" => Some("subshell"),
        "heredocs" => Some("heredoc"),
        "function_definitions" => Some("function_def"),
        _ => None,
    }
}

pub fn import(cc_toml: &str) -> Result<Import, String> {
    let root: toml::Value = cc_toml.parse().map_err(|e| format!("not valid TOML: {e}"))?;
    let mut out = Import::default();
    let mut doc = String::from("# generated by `vouch import`\nversion = 1\n");

    let get = |path: &[&str]| -> Option<&toml::Value> {
        let mut cur = &root;
        for p in path {
            cur = cur.get(p)?;
        }
        Some(cur)
    };

    // --- bash -------------------------------------------------------------
    let bash_default = action_of(get(&["bash", "default"])).unwrap_or("ask");
    doc.push_str(&format!("\n[lang.bash]\ndefault = \"{bash_default}\"\n"));

    let mut constructs: BTreeMap<String, String> = BTreeMap::new();
    if let Some(a) = action_of(get(&["bash", "dynamic_commands"])) {
        constructs.insert("dynamic_command".into(), a.into());
        constructs.insert("dynamic_redirect".into(), a.into());
        out.notes.push(format!(
            "bash.dynamic_commands = \"{a}\" -> dynamic_command AND dynamic_redirect \
             (cc-allow used one switch for both; vouch splits them)"
        ));
    }
    if let Some(a) = action_of(get(&["bash", "unresolved_commands"])) {
        constructs.insert("unmodeled_command".into(), a.into());
    }
    if let Some(tbl) = get(&["bash", "constructs"]).and_then(|v| v.as_table()) {
        for (k, v) in tbl {
            match construct_map(k) {
                Some(name) => {
                    if let Some(a) = action_of(Some(v)) {
                        constructs.insert(name.into(), a.into());
                    }
                }
                None => out
                    .notes
                    .push(format!("bash.constructs.{k}: no vouch equivalent, dropped")),
            }
        }
    }
    // vouch has constructs cc-allow never had; leave them unset so they ask.
    if !constructs.is_empty() {
        doc.push_str("\n[lang.bash.constructs]\n");
        for (k, v) in &constructs {
            doc.push_str(&format!("{k} = \"{v}\"\n"));
        }
    }

    // --- powershell -------------------------------------------------------
    // cc-allow paired `powershell.default = "ask"` with a list of trusted program
    // NAMES. vouch does not gate on names and that list is deliberately not
    // imported, so carrying "ask" across would prompt on EVERY PowerShell command
    // — precisely the behaviour being replaced. Translate the intent instead.
    let ps_had_namelist = get(&["powershell", "allow", "commands"])
        .and_then(|v| v.as_array())
        .map(|a| !a.is_empty())
        .unwrap_or(false);
    if let Some(a) = action_of(get(&["powershell", "default"])) {
        let effective = if a == "ask" && ps_had_namelist { "allow" } else { a };
        doc.push_str(&format!("\n[lang.powershell]\ndefault = \"{effective}\"\n"));
        if effective != a {
            out.notes.push(format!(
                "powershell.default was \"{a}\", paired with a program-name allowlist. \
                 Imported as \"allow\": vouch gates PowerShell by guards and write \
                 rules, not by program name, so keeping \"ask\" would prompt on every \
                 single PowerShell command."
            ));
        }
        // The constructs cc-allow hard-coded to prompt with no setting at all —
        // the original complaint. Here they are settings, and they are set.
        doc.push_str(
            "\n[lang.powershell.constructs]\n\
             # cc-allow prompted on these with no setting that could change it.\n\
             type_literal = \"allow\"\n\
             call_operator = \"allow\"\n\
             method_call = \"allow\"\n\
             keyword_foreach = \"allow\"\n\
             keyword_while = \"allow\"\n\
             keyword_do = \"allow\"\n\
             keyword_switch = \"allow\"\n\
             keyword_try = \"allow\"\n\
             assignment = \"allow\"\n\
             env_assignment = \"allow\"\n\
             redirect = \"allow\"\n\
             function_def = \"allow\"\n\
             unmodeled_command = \"allow\"\n\
             # vouch's own defects stay visible\n\
             parse_failure = \"ask\"\n\
             unbalanced_quotes = \"ask\"\n",
        );
        out.notes.push(
            "[lang.powershell.constructs] written with the blind-spot constructs allowed — \
             the ones cc-allow hard-coded to prompt with no setting. parse_failure \
             stays \"ask\" so vouch's own defects remain visible."
                .into(),
        );
    }

    // --- write / edit paths ----------------------------------------------
    let mut paths: Vec<String> = Vec::new();
    for section in ["write", "edit"] {
        if let Some(arr) = get(&[section, "allow", "paths"]).and_then(|v| v.as_array()) {
            for p in arr.iter().filter_map(|v| v.as_str()) {
                let cleaned = p.strip_prefix("path:").unwrap_or(p).to_string();
                if !paths.contains(&cleaned) {
                    paths.push(cleaned);
                }
            }
        }
    }
    // cc-allow needed a duplicate C:/c/... entry per real path because it could
    // not canonicalise MSYS paths. vouch canonicalises, so the twins collapse.
    let before = paths.len();
    paths.retain(|p| !p.to_lowercase().starts_with("c:/c/"));
    let collapsed = before - paths.len();
    if collapsed > 0 {
        out.notes.push(format!(
            "{collapsed} duplicate 'C:/c/...' path entries dropped — they existed only \
             because cc-allow could not canonicalise MSYS paths. vouch does, so one entry covers both."
        ));
    }
    if !paths.is_empty() {
        let wdefault = action_of(get(&["write", "default"])).unwrap_or("ask");
        doc.push_str(&format!("\n[write]\ndefault = \"{wdefault}\"\nallow_paths = [\n"));
        for p in &paths {
            doc.push_str(&format!("  \"{p}\",\n"));
        }
        doc.push_str("]\n");
    }

    // --- things that deliberately do NOT translate ------------------------
    if let Some(arr) = get(&["bash", "allow", "commands"]).and_then(|v| v.as_array()) {
        if !arr.is_empty() {
            out.notes.push(format!(
                "{} bash command-name allowances NOT imported. vouch does not gate on \
                 program names — it gates on what a program does. Rebuilding a name \
                 allowlist would recreate the mechanism that caused 575 prompts.",
                arr.len()
            ));
        }
    }
    if let Some(arr) = get(&["powershell", "allow", "commands"]).and_then(|v| v.as_array()) {
        if !arr.is_empty() {
            out.notes.push(format!(
                "{} powershell command-name allowances NOT imported, same reason.",
                arr.len()
            ));
        }
    }
    if let Some(arr) = get(&["tools", "allow"]).and_then(|v| v.as_array()) {
        out.notes.push(format!(
            "[tools] section ({} entries) NOT imported — but vouch does have an \
             equivalent, so this is a translation gap rather than a missing feature. \
             An unrecognised tool ASKS here (it does not abstain), naming \
             `tools.<name>` as the setting that allows it. Write `tools.<name> = \
             \"allow\"` for each you want ungated, or describe the tool properly with \
             a `[[tool]]` entry — the vouch-trust skill proposes the narrowest one. \
             Names, in your old file: {}",
            arr.len(),
            arr.iter()
                .filter_map(|v| v.as_str())
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }

    // Always protect vouch's own files.
    doc.push_str(
        "\n[protected]\n\
         # never silently writable, by identity. No setting opens these.\n\
         paths = [\"$HOME/.claude/settings.json\", \"$HOME/.config/vouch/config.toml\"]\n",
    );

    out.config = doc;
    Ok(out)
}
