//! `vouch install` & `vouch uninstall` — manage hook registrations across hosts.
//!
//! Generates merged hook configuration for Claude Code (`settings.json`), OpenAI
//! Codex (`hooks.json`), and Google Antigravity (`hooks.json`). Emits merged JSON
//! to standard output for manual review/redirection, or atomically writes to the
//! host's configuration file when `--write` is specified (backed up with rollback).
//! `vouch uninstall` cleanly strips vouch registrations while preserving unrelated
//! hooks and MCP configurations.
//!
//! For Claude Code, four events are registered:
//!   PreToolUse         — the decision
//!   PostToolUse        — "it ran"
//!   PostToolUseFailure — "it errored or was interrupted"
//!   PermissionDenied   — "the user refused it"
//!
//! For Codex and Antigravity, `PreToolUse` gates decisions and `PostToolUse`
//! records outcomes. The outcome events exist so `vouch review` is built on real
//! outcomes rather than on the absence of a signal.

use serde_json::{json, Value};

use crate::cli::{validate_state_dir, InstallShell};

const CODEX_STATUS_MESSAGE: &str = "vouch is checking this tool call";

pub struct Plan {
    /// The settings.json content to save.
    pub settings: String,
    /// The hooks-only view — display-safe: no MCP/server content, whatever
    /// else the operator's settings.json carries.
    pub hooks_view: String,
    /// What this changes, in plain terms.
    pub notes: Vec<String>,
}

fn hook_entry(exe: &str, extra: &str) -> Value {
    json!({ "hooks": [ { "type": "command", "command": hook_command(exe, extra) } ] })
}

fn hook_command(exe: &str, extra: &str) -> String {
    let exe = if exe.contains(' ') { format!("\"{exe}\"") } else { exe.to_string() };
    if extra.is_empty() { format!("{exe} --hook") } else { format!("{exe} --hook {extra}") }
}

/// Return the executable for a Claude hook command generated by vouch.
/// Matching the basename plus the complete suffix distinguishes an old vouch
/// registration from unrelated commands that merely contain the word.
fn vouch_exe_of(command: &str) -> Option<&str> {
    let rest = command
        .strip_suffix(" --hook --shadow")
        .or_else(|| command.strip_suffix(" --hook"))?;
    let exe = rest.strip_prefix('"').and_then(|v| v.strip_suffix('"')).unwrap_or(rest);
    let base = exe.rsplit(['/', '\\']).next().unwrap_or(exe);
    (base.eq_ignore_ascii_case("vouch") || base.eq_ignore_ascii_case("vouch.exe")).then_some(exe)
}

#[derive(Default)]
struct Repointed {
    found: bool,
    moved: usize,
    stood_down: usize,
}

/// Repoint generated Claude vouch hooks while retaining unrelated neighbours.
fn repoint(entries: &mut [Value], exe: &str, force_shadow: bool) -> Repointed {
    let mut result = Repointed::default();
    for group in entries {
        let Some(hooks) = group.get_mut("hooks").and_then(Value::as_array_mut) else { continue };
        for hook in hooks {
            let command = hook.get("command").and_then(Value::as_str).unwrap_or_default().to_string();
            let Some(old_exe) = vouch_exe_of(&command) else { continue };
            result.found = true;
            let was_shadow = command.ends_with(" --shadow");
            if old_exe != exe { result.moved += 1; }
            if force_shadow && !was_shadow { result.stood_down += 1; }
            let wanted = hook_command(exe, if force_shadow || was_shadow { "--shadow" } else { "" });
            if wanted != command { hook["command"] = json!(wanted); }
        }
    }
    result
}

fn bash_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn powershell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn codex_command(
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: Option<&str>,
) -> String {
    let quoted = match shell {
        InstallShell::Bash => bash_quote(exe),
        InstallShell::PowerShell => format!("& {}", powershell_quote(exe)),
    };
    let shadow = if shadow { " --shadow" } else { "" };
    let state_dir = state_dir
        .map(|path| match shell {
            InstallShell::Bash => format!(" --state-dir {}", bash_quote(path)),
            InstallShell::PowerShell => format!(" --state-dir {}", powershell_quote(path)),
        })
        .unwrap_or_default();
    format!(
        "{quoted} --hook --host codex --shell {}{shadow}{state_dir}",
        shell.as_str()
    )
}

fn codex_hook_entry(
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: Option<&str>,
) -> Value {
    json!({
        "matcher": ".*",
        "hooks": [{
            "type": "command",
            "command": codex_command(exe, shell, shadow, state_dir),
            "timeout": 30,
            "statusMessage": CODEX_STATUS_MESSAGE
        }]
    })
}

fn is_codex_vouch_hook(hook: &Value) -> bool {
    hook.get("type").and_then(Value::as_str) == Some("command")
        && hook.get("statusMessage").and_then(Value::as_str) == Some(CODEX_STATUS_MESSAGE)
        && hook
            .get("command")
            .and_then(Value::as_str)
            .is_some_and(|command| command.contains("--hook --host codex"))
}

fn without_codex_vouch(entries: Option<&Value>, event: &str) -> Result<Vec<Value>, String> {
    let Some(entries) = entries else {
        return Ok(Vec::new());
    };
    let entries = entries
        .as_array()
        .ok_or_else(|| format!("hooks.json {event:?} hooks are not an array"))?;
    let mut kept = Vec::new();
    for entry in entries {
        let mut entry = entry.clone();
        let Some(hooks) = entry.get_mut("hooks").and_then(Value::as_array_mut) else {
            kept.push(entry);
            continue;
        };
        hooks.retain(|hook| !is_codex_vouch_hook(hook));
        if !hooks.is_empty() {
            kept.push(entry);
        }
    }
    Ok(kept)
}

/// Build a merged `~/.codex/hooks.json`. Codex owns its native sandbox and
/// approval policy; this file only installs vouch's local PreToolUse decision
/// hook and PostToolUse outcome recorder. Unrelated hooks are never replaced.
pub fn plan_codex(
    existing: &str,
    exe: &str,
    shell: InstallShell,
    shadow: bool,
) -> Result<Plan, String> {
    plan_codex_inner(existing, exe, shell, shadow, None)
}

/// The durable-journal form of [`plan_codex`]. The state directory is an
/// explicit hook argument rather than an assumed inherited environment value.
pub fn plan_codex_with_state(
    existing: &str,
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: &str,
) -> Result<Plan, String> {
    validate_state_dir(state_dir)?;
    plan_codex_inner(existing, exe, shell, shadow, Some(state_dir))
}

fn plan_codex_inner(
    existing: &str,
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: Option<&str>,
) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing).map_err(|e| format!("hooks.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("hooks.json is not a JSON object".into());
    }
    let hooks = root
        .as_object_mut()
        .unwrap()
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .ok_or("hooks.json 'hooks' is not an object")?;

    for (event, event_shadow) in [("PreToolUse", shadow), ("PostToolUse", false)] {
        let mut entries = without_codex_vouch(hooks.get(event), event)?;
        entries.push(codex_hook_entry(exe, shell, event_shadow, state_dir));
        hooks.insert(event.to_string(), Value::Array(entries));
    }

    let broker_name = if exe.to_ascii_lowercase().ends_with(".exe") {
        "vouch-codex-broker.exe"
    } else {
        "vouch-codex-broker"
    };
    let broker = std::path::Path::new(exe)
        .with_file_name(broker_name)
        .to_string_lossy()
        .replace('\\', "/");
    let broker = if broker.contains(' ') {
        format!("\"{broker}\"")
    } else {
        broker
    };
    let mut notes = vec![
        if shadow {
            "SHADOW: vouch records what it would decide and emits no decision; Codex remains in charge."
        } else {
            "LIVE: vouch blocks Codex tool calls it would ask about or deny."
        }
        .into(),
        "Codex PostToolUse records completed calls; unsupported Claude-only outcome events are not installed."
            .into(),
        if state_dir.is_some() {
            "Both Codex hooks use the explicit stable --state-dir."
        } else {
            "No --state-dir was supplied; hooks use inherited VOUCH_STATE_DIR or the OS temp fallback."
        }
        .into(),
    ];
    if shadow {
        notes.push(
            "Passive shadow needs no vouch approval broker and leaves Codex's approval policy and reviewer unchanged."
                .into(),
        );
    } else {
        notes.push(format!(
            "Register the one-time human approval broker once: codex mcp add vouch_approval -- {broker}"
        ));
        notes.push(
            "Configure Codex for interactive human approval: approval_policy = \"on-request\", approvals_reviewer = \"user\", and under [mcp_servers.vouch_approval] set default_tools_approval_mode = \"prompt\". The native MCP prompt is the broker decision; no nested elicitation is used."
                .into(),
        );
    }
    let hooks_view = serde_json::to_string_pretty(&json!({ "hooks": root["hooks"].clone() }))
        .map_err(|e| e.to_string())?;
    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render hooks.json: {e}"))?;
    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

fn agy_command(exe: &str, shadow: bool, state_dir: Option<&str>) -> String {
    let quoted = if exe.contains(' ') {
        format!("\"{exe}\"")
    } else {
        exe.to_string()
    };
    let shadow_str = if shadow { " --shadow" } else { "" };
    let state_dir_str = state_dir
        .map(|path| {
            if path.contains(' ') {
                format!(" --state-dir \"{path}\"")
            } else {
                format!(" --state-dir {path}")
            }
        })
        .unwrap_or_default();
    format!("{quoted} --hook --host agy{shadow_str}{state_dir_str}")
}

fn agy_hook_entry(exe: &str, shadow: bool, state_dir: Option<&str>) -> Value {
    json!({
        "matcher": "run_command|write_to_file|replace_file_content",
        "hooks": [{
            "type": "command",
            "command": agy_command(exe, shadow, state_dir)
        }]
    })
}

/// Build a merged Antigravity `hooks.json`.
pub fn plan_agy(
    existing: &str,
    exe: &str,
    shadow: bool,
    state_dir: Option<&str>,
) -> Result<Plan, String> {
    if let Some(path) = state_dir {
        validate_state_dir(path)?;
    }
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing).map_err(|e| format!("hooks.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("hooks.json is not a JSON object".into());
    }

    let pre_entry = agy_hook_entry(exe, shadow, state_dir);
    let post_entry = agy_hook_entry(exe, false, state_dir);

    let vouch_group = json!({
        "PreToolUse": [pre_entry],
        "PostToolUse": [post_entry]
    });

    root.as_object_mut()
        .unwrap()
        .insert("vouch".to_string(), vouch_group);

    let mut notes = vec![
        if shadow {
            "SHADOW: vouch records what it would decide and emits no decision; Antigravity remains in charge."
        } else {
            "LIVE: vouch gates Antigravity tool calls (run_command, write_to_file, replace_file_content)."
        }
        .into(),
        "Antigravity PreToolUse evaluates tool calls; PostToolUse records outcomes.".into(),
        "Antigravity PreToolUse automatically allows safe operations without interactive prompts.".into(),
    ];
    if state_dir.is_some() {
        notes.push("Both Antigravity hooks use the explicit stable --state-dir.".into());
    } else {
        notes.push("No --state-dir was supplied; hooks use inherited VOUCH_STATE_DIR or the OS temp fallback.".into());
    }

    let hooks_view = serde_json::to_string_pretty(&json!({ "vouch": root["vouch"].clone() }))
        .map_err(|e| e.to_string())?;
    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render hooks.json: {e}"))?;

    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

/// Builds the merged settings.json. `shadow` keeps the existing gate in place and
/// adds vouch alongside it, recording decisions without being able to affect any.
pub fn plan(existing: &str, exe: &str, shadow: bool) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing)
            .map_err(|e| format!("settings.json is not valid JSON: {e}"))?
    };
    let mut notes = Vec::new();

    if !root.is_object() {
        return Err("settings.json is not a JSON object".into());
    }
    let obj = root.as_object_mut().unwrap();
    let hooks = obj
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .ok_or("settings.json 'hooks' is not an object")?;

    // What is gating today?
    let existing_pre = hooks.get("PreToolUse").cloned().unwrap_or(json!([]));
    let existing_txt = existing_pre.to_string();
    let had_cc_allow = existing_txt.contains("cc-allow");
    let vouch_pre = hook_entry(exe, if shadow { "--shadow" } else { "" });

    let mut repointed = 0;
    let mut stood_down = 0;

    if shadow {
        // Keep whatever is there; append vouch. It emits nothing, by construction.
        let mut arr = existing_pre.as_array().cloned().unwrap_or_default();
        let result = repoint(&mut arr, exe, true);
        repointed += result.moved;
        stood_down += result.stood_down;
        if !result.found {
            arr.push(vouch_pre);
        }
        hooks.insert("PreToolUse".into(), Value::Array(arr));
        notes.push(
            "SHADOW: the existing gate still decides everything. vouch is added \
             alongside it and emits nothing — there is a test asserting that. It only \
             records what it would have decided."
                .into(),
        );
        if had_cc_allow {
            notes.push("cc-allow is left wired and still in charge.".into());
        }
    } else {
        hooks.insert("PreToolUse".into(), json!([vouch_pre]));
        notes.push("LIVE: vouch is now the gate for PreToolUse.".into());
        if had_cc_allow {
            notes.push(
                "cc-allow was REMOVED from PreToolUse. Its config file is untouched, \
                 so putting it back is one edit."
                    .into(),
            );
        }
    }

    // Outcome events. Harmless in either mode — they only record.
    let mut added = Vec::new();
    for ev in ["PostToolUse", "PostToolUseFailure", "PermissionDenied"] {
        let mut arr = hooks
            .get(ev)
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();
        let result = repoint(&mut arr, exe, false);
        repointed += result.moved;
        if !result.found {
            arr.push(hook_entry(exe, ""));
            added.push(ev);
        }
        hooks.insert(ev.to_string(), Value::Array(arr));
    }
    if !added.is_empty() {
        notes.push(format!(
            "{} added: these only record what actually happened. Without them \
             `vouch review` would be guessing.",
            added.join(" / ")
        ));
    }
    if repointed > 0 {
        notes.push(format!(
            "{repointed} existing vouch hook(s) named a different executable and were \
             repointed at this one."
        ));
    }
    if stood_down > 0 {
        notes.push(format!(
            "{stood_down} existing vouch hook(s) was deciding and has been stood down to \
             --shadow, because shadow must not promote a new binary into the live gate."
        ));
    }

    let hooks_view = serde_json::to_string_pretty(&json!({ "hooks": root["hooks"].clone() }))
        .map_err(|e| e.to_string())?;

    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render settings.json: {e}"))?;
    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

/// Remove vouch hooks from Claude Code's settings.json.
pub fn unplan(existing: &str) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing)
            .map_err(|e| format!("settings.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("settings.json is not a JSON object".into());
    }

    let mut removed = 0;
    if let Some(hooks) = root.get_mut("hooks").and_then(Value::as_object_mut) {
        let events = ["PreToolUse", "PostToolUse", "PostToolUseFailure", "PermissionDenied"];
        for ev in events {
            if let Some(groups) = hooks.get_mut(ev).and_then(Value::as_array_mut) {
                for group in groups.iter_mut() {
                    if let Some(hook_list) = group.get_mut("hooks").and_then(Value::as_array_mut) {
                        let before = hook_list.len();
                        hook_list.retain(|hook| {
                            let command = hook.get("command").and_then(Value::as_str).unwrap_or_default();
                            vouch_exe_of(command).is_none()
                        });
                        removed += before - hook_list.len();
                    }
                }
                groups.retain(|group| {
                    group.get("hooks").and_then(Value::as_array).is_some_and(|h| !h.is_empty())
                });
            }
            if hooks.get(ev).and_then(Value::as_array).is_some_and(|g| g.is_empty()) {
                hooks.remove(ev);
            }
        }
        if hooks.is_empty() {
            root.as_object_mut().unwrap().remove("hooks");
        }
    }

    let notes = if removed > 0 {
        vec![format!("{removed} vouch hook(s) removed from Claude settings.json.")]
    } else {
        vec!["No vouch hooks were found in Claude settings.json.".into()]
    };

    let hooks_view = if let Some(hooks) = root.get("hooks") {
        serde_json::to_string_pretty(&json!({ "hooks": hooks.clone() })).map_err(|e| e.to_string())?
    } else {
        "{}".into()
    };
    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render settings.json: {e}"))?;

    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

/// Remove vouch hooks from Codex's hooks.json.
pub fn unplan_codex(existing: &str) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing)
            .map_err(|e| format!("hooks.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("hooks.json is not a JSON object".into());
    }

    let mut removed = false;
    if let Some(hooks) = root.get_mut("hooks").and_then(Value::as_object_mut) {
        for event in ["PreToolUse", "PostToolUse"] {
            let before_count = hooks.get(event).and_then(Value::as_array).map(|a| a.len()).unwrap_or(0);
            let kept = without_codex_vouch(hooks.get(event), event)?;
            if kept.len() < before_count {
                removed = true;
            }
            if kept.is_empty() {
                hooks.remove(event);
            } else {
                hooks.insert(event.to_string(), Value::Array(kept));
            }
        }
        if hooks.is_empty() {
            root.as_object_mut().unwrap().remove("hooks");
        }
    }

    let mut notes = Vec::new();
    if removed {
        notes.push("vouch hooks removed from Codex hooks.json.".into());
        notes.push("Note: to remove the vouch_approval MCP broker from Codex, run: codex mcp remove vouch_approval".into());
    } else {
        notes.push("No vouch hooks were found in Codex hooks.json.".into());
    }

    let hooks_view = if let Some(hooks) = root.get("hooks") {
        serde_json::to_string_pretty(&json!({ "hooks": hooks.clone() })).map_err(|e| e.to_string())?
    } else {
        "{}".into()
    };
    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render hooks.json: {e}"))?;

    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

/// Remove vouch hooks from Antigravity's hooks.json.
pub fn unplan_agy(existing: &str) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing)
            .map_err(|e| format!("hooks.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("hooks.json is not a JSON object".into());
    }

    let removed = root.as_object_mut().unwrap().remove("vouch").is_some();
    let notes = if removed {
        vec!["vouch hook group removed from Antigravity hooks.json.".into()]
    } else {
        vec!["No vouch hook group was found in Antigravity hooks.json.".into()]
    };

    let hooks_view = serde_json::to_string_pretty(&root).map_err(|e| e.to_string())?;
    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render hooks.json: {e}"))?;

    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

/// Write configuration atomically to `path`, creating any missing parent directories.
pub fn write_file_atomically(path: &std::path::Path, content: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("could not create directory {}: {e}", parent.display()))?;
    }
    let temp_name = format!(
        ".{}.tmp.{}",
        path.file_name().and_then(|n| n.to_str()).unwrap_or("config"),
        std::process::id()
    );
    let temp_path = path.with_file_name(temp_name);
    if std::fs::write(&temp_path, content).is_ok() && std::fs::rename(&temp_path, path).is_ok() {
        return Ok(());
    }
    let _ = std::fs::remove_file(&temp_path);
    std::fs::write(path, content)
        .map_err(|e| format!("could not write {}: {e}", path.display()))?;
    Ok(())
}

/// Standard modeled developer tools requiring unsandboxed execution under Antigravity.
pub const DEFAULT_AGY_UNSANDBOXED_TOOLS: &[&str] = &["cargo*", "gh*", "git*", "curl*", "ssh*"];

/// Reconciles Antigravity settings.json permissions to include clean tool entries.
pub fn reconcile_agy_permissions(existing: &str, tools: &[&str]) -> Result<String, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing)
            .map_err(|e| format!("settings.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("settings.json is not a JSON object".into());
    }
    let perms = root
        .as_object_mut()
        .unwrap()
        .entry("permissions")
        .or_insert_with(|| json!({}));
    if !perms.is_object() {
        *perms = json!({});
    }
    let allow = perms
        .as_object_mut()
        .unwrap()
        .entry("allow")
        .or_insert_with(|| json!([]));
    if let Some(arr) = allow.as_array_mut() {
        for tool in tools {
            let entry = Value::String(format!("unsandboxed({tool})"));
            if !arr.contains(&entry) {
                arr.push(entry);
            }
        }
    }
    serde_json::to_string_pretty(&root).map_err(|e| format!("could not render settings.json: {e}"))
}

