//! `vouch install --print` — emit the exact hook registration vouch needs.
//!
//! vouch cannot write `settings.json` itself: Claude Code's own guard refuses to
//! let an agent change which program gates its tool calls. That guard is correct
//! and is not worked around. So this produces the exact JSON, merged with what is
//! already there, for a human to save.
//!
//! Four events are needed, and only the first one decides anything:
//!   PreToolUse         — the decision
//!   PostToolUse        — "it ran"
//!   PostToolUseFailure — "it errored or was interrupted"
//!   PermissionDenied   — "the user refused it"
//!
//! The last three exist so `vouch review` is built on real outcomes rather than
//! on the absence of a signal, which is the mistake that killed the first design.

use serde_json::{json, Value};

use crate::cli::{validate_state_dir, InstallShell};

const CODEX_STATUS_MESSAGE: &str = "vouch is checking this tool call";

pub struct Plan {
    /// The settings.json content to save.
    pub settings: String,
    /// The hooks-only view — display-safe: no MCP/server content, whatever
    /// else the operator's settings.json carries.
    pub hooks_view: String,
    /// What this changes, in plain terms.
    pub notes: Vec<String>,
}

fn hook_entry(exe: &str, extra: &str) -> Value {
    json!({ "hooks": [ { "type": "command", "command": hook_command(exe, extra) } ] })
}

fn hook_command(exe: &str, extra: &str) -> String {
    let exe = if exe.contains(' ') { format!("\"{exe}\"") } else { exe.to_string() };
    if extra.is_empty() { format!("{exe} --hook") } else { format!("{exe} --hook {extra}") }
}

/// Return the executable for a Claude hook command generated by vouch.
/// Matching the basename plus the complete suffix distinguishes an old vouch
/// registration from unrelated commands that merely contain the word.
fn vouch_exe_of(command: &str) -> Option<&str> {
    let rest = command
        .strip_suffix(" --hook --shadow")
        .or_else(|| command.strip_suffix(" --hook"))?;
    let exe = rest.strip_prefix('"').and_then(|v| v.strip_suffix('"')).unwrap_or(rest);
    let base = exe.rsplit(['/', '\\']).next().unwrap_or(exe);
    (base.eq_ignore_ascii_case("vouch") || base.eq_ignore_ascii_case("vouch.exe")).then_some(exe)
}

#[derive(Default)]
struct Repointed {
    found: bool,
    moved: usize,
    stood_down: usize,
}

/// Repoint generated Claude vouch hooks while retaining unrelated neighbours.
fn repoint(entries: &mut [Value], exe: &str, force_shadow: bool) -> Repointed {
    let mut result = Repointed::default();
    for group in entries {
        let Some(hooks) = group.get_mut("hooks").and_then(Value::as_array_mut) else { continue };
        for hook in hooks {
            let command = hook.get("command").and_then(Value::as_str).unwrap_or_default().to_string();
            let Some(old_exe) = vouch_exe_of(&command) else { continue };
            result.found = true;
            let was_shadow = command.ends_with(" --shadow");
            if old_exe != exe { result.moved += 1; }
            if force_shadow && !was_shadow { result.stood_down += 1; }
            let wanted = hook_command(exe, if force_shadow || was_shadow { "--shadow" } else { "" });
            if wanted != command { hook["command"] = json!(wanted); }
        }
    }
    result
}

fn bash_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn powershell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn codex_command(
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: Option<&str>,
) -> String {
    let quoted = match shell {
        InstallShell::Bash => bash_quote(exe),
        InstallShell::PowerShell => format!("& {}", powershell_quote(exe)),
    };
    let shadow = if shadow { " --shadow" } else { "" };
    let state_dir = state_dir
        .map(|path| match shell {
            InstallShell::Bash => format!(" --state-dir {}", bash_quote(path)),
            InstallShell::PowerShell => format!(" --state-dir {}", powershell_quote(path)),
        })
        .unwrap_or_default();
    format!(
        "{quoted} --hook --host codex --shell {}{shadow}{state_dir}",
        shell.as_str()
    )
}

fn codex_hook_entry(
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: Option<&str>,
) -> Value {
    json!({
        "matcher": ".*",
        "hooks": [{
            "type": "command",
            "command": codex_command(exe, shell, shadow, state_dir),
            "timeout": 30,
            "statusMessage": CODEX_STATUS_MESSAGE
        }]
    })
}

fn is_codex_vouch_hook(hook: &Value) -> bool {
    hook.get("type").and_then(Value::as_str) == Some("command")
        && hook.get("statusMessage").and_then(Value::as_str) == Some(CODEX_STATUS_MESSAGE)
        && hook
            .get("command")
            .and_then(Value::as_str)
            .is_some_and(|command| command.contains("--hook --host codex"))
}

fn without_codex_vouch(entries: Option<&Value>, event: &str) -> Result<Vec<Value>, String> {
    let Some(entries) = entries else {
        return Ok(Vec::new());
    };
    let entries = entries
        .as_array()
        .ok_or_else(|| format!("hooks.json {event:?} hooks are not an array"))?;
    let mut kept = Vec::new();
    for entry in entries {
        let mut entry = entry.clone();
        let Some(hooks) = entry.get_mut("hooks").and_then(Value::as_array_mut) else {
            kept.push(entry);
            continue;
        };
        hooks.retain(|hook| !is_codex_vouch_hook(hook));
        if !hooks.is_empty() {
            kept.push(entry);
        }
    }
    Ok(kept)
}

/// Build a merged `~/.codex/hooks.json`. Codex owns its native sandbox and
/// approval policy; this file only installs vouch's local PreToolUse decision
/// hook and PostToolUse outcome recorder. Unrelated hooks are never replaced.
pub fn plan_codex(
    existing: &str,
    exe: &str,
    shell: InstallShell,
    shadow: bool,
) -> Result<Plan, String> {
    plan_codex_inner(existing, exe, shell, shadow, None)
}

/// The durable-journal form of [`plan_codex`]. The state directory is an
/// explicit hook argument rather than an assumed inherited environment value.
pub fn plan_codex_with_state(
    existing: &str,
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: &str,
) -> Result<Plan, String> {
    validate_state_dir(state_dir)?;
    plan_codex_inner(existing, exe, shell, shadow, Some(state_dir))
}

fn plan_codex_inner(
    existing: &str,
    exe: &str,
    shell: InstallShell,
    shadow: bool,
    state_dir: Option<&str>,
) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing).map_err(|e| format!("hooks.json is not valid JSON: {e}"))?
    };
    if !root.is_object() {
        return Err("hooks.json is not a JSON object".into());
    }
    let hooks = root
        .as_object_mut()
        .unwrap()
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .ok_or("hooks.json 'hooks' is not an object")?;

    for (event, event_shadow) in [("PreToolUse", shadow), ("PostToolUse", false)] {
        let mut entries = without_codex_vouch(hooks.get(event), event)?;
        entries.push(codex_hook_entry(exe, shell, event_shadow, state_dir));
        hooks.insert(event.to_string(), Value::Array(entries));
    }

    let broker_name = if exe.to_ascii_lowercase().ends_with(".exe") {
        "vouch-codex-broker.exe"
    } else {
        "vouch-codex-broker"
    };
    let broker = std::path::Path::new(exe)
        .with_file_name(broker_name)
        .to_string_lossy()
        .replace('\\', "/");
    let broker = if broker.contains(' ') {
        format!("\"{broker}\"")
    } else {
        broker
    };
    let mut notes = vec![
        if shadow {
            "SHADOW: vouch records what it would decide and emits no decision; Codex remains in charge."
        } else {
            "LIVE: vouch blocks Codex tool calls it would ask about or deny."
        }
        .into(),
        "Codex PostToolUse records completed calls; unsupported Claude-only outcome events are not installed."
            .into(),
        if state_dir.is_some() {
            "Both Codex hooks use the explicit stable --state-dir."
        } else {
            "No --state-dir was supplied; hooks use inherited VOUCH_STATE_DIR or the OS temp fallback."
        }
        .into(),
    ];
    if shadow {
        notes.push(
            "Passive shadow needs no vouch approval broker and leaves Codex's approval policy and reviewer unchanged."
                .into(),
        );
    } else {
        notes.push(format!(
            "Register the one-time human approval broker once: codex mcp add vouch_approval -- {broker}"
        ));
        notes.push(
            "Configure Codex for interactive human approval: approval_policy = \"on-request\", approvals_reviewer = \"user\", and under [mcp_servers.vouch_approval] set default_tools_approval_mode = \"prompt\". The native MCP prompt is the broker decision; no nested elicitation is used."
                .into(),
        );
    }
    let hooks_view = serde_json::to_string_pretty(&json!({ "hooks": root["hooks"].clone() }))
        .map_err(|e| e.to_string())?;
    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render hooks.json: {e}"))?;
    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}

/// Builds the merged settings.json. `shadow` keeps the existing gate in place and
/// adds vouch alongside it, recording decisions without being able to affect any.
pub fn plan(existing: &str, exe: &str, shadow: bool) -> Result<Plan, String> {
    let mut root: Value = if existing.trim().is_empty() {
        json!({})
    } else {
        serde_json::from_str(existing)
            .map_err(|e| format!("settings.json is not valid JSON: {e}"))?
    };
    let mut notes = Vec::new();

    if !root.is_object() {
        return Err("settings.json is not a JSON object".into());
    }
    let obj = root.as_object_mut().unwrap();
    let hooks = obj
        .entry("hooks")
        .or_insert_with(|| json!({}))
        .as_object_mut()
        .ok_or("settings.json 'hooks' is not an object")?;

    // What is gating today?
    let existing_pre = hooks.get("PreToolUse").cloned().unwrap_or(json!([]));
    let existing_txt = existing_pre.to_string();
    let had_cc_allow = existing_txt.contains("cc-allow");
    let vouch_pre = hook_entry(exe, if shadow { "--shadow" } else { "" });

    let mut repointed = 0;
    let mut stood_down = 0;

    if shadow {
        // Keep whatever is there; append vouch. It emits nothing, by construction.
        let mut arr = existing_pre.as_array().cloned().unwrap_or_default();
        let result = repoint(&mut arr, exe, true);
        repointed += result.moved;
        stood_down += result.stood_down;
        if !result.found {
            arr.push(vouch_pre);
        }
        hooks.insert("PreToolUse".into(), Value::Array(arr));
        notes.push(
            "SHADOW: the existing gate still decides everything. vouch is added \
             alongside it and emits nothing — there is a test asserting that. It only \
             records what it would have decided."
                .into(),
        );
        if had_cc_allow {
            notes.push("cc-allow is left wired and still in charge.".into());
        }
    } else {
        hooks.insert("PreToolUse".into(), json!([vouch_pre]));
        notes.push("LIVE: vouch is now the gate for PreToolUse.".into());
        if had_cc_allow {
            notes.push(
                "cc-allow was REMOVED from PreToolUse. Its config file is untouched, \
                 so putting it back is one edit."
                    .into(),
            );
        }
    }

    // Outcome events. Harmless in either mode — they only record.
    let mut added = Vec::new();
    for ev in ["PostToolUse", "PostToolUseFailure", "PermissionDenied"] {
        let mut arr = hooks
            .get(ev)
            .and_then(|v| v.as_array())
            .cloned()
            .unwrap_or_default();
        let result = repoint(&mut arr, exe, false);
        repointed += result.moved;
        if !result.found {
            arr.push(hook_entry(exe, ""));
            added.push(ev);
        }
        hooks.insert(ev.to_string(), Value::Array(arr));
    }
    if !added.is_empty() {
        notes.push(format!(
            "{} added: these only record what actually happened. Without them \
             `vouch review` would be guessing.",
            added.join(" / ")
        ));
    }
    if repointed > 0 {
        notes.push(format!(
            "{repointed} existing vouch hook(s) named a different executable and were \
             repointed at this one."
        ));
    }
    if stood_down > 0 {
        notes.push(format!(
            "{stood_down} existing vouch hook(s) was deciding and has been stood down to \
             --shadow, because shadow must not promote a new binary into the live gate."
        ));
    }

    let hooks_view = serde_json::to_string_pretty(&json!({ "hooks": root["hooks"].clone() }))
        .map_err(|e| e.to_string())?;

    let settings = serde_json::to_string_pretty(&root)
        .map_err(|e| format!("could not render settings.json: {e}"))?;
    Ok(Plan {
        settings,
        hooks_view,
        notes,
    })
}
